config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

 
root 'welcomes#home'

get 'about', to: 'welcomes#about'

resources :articles


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum: 3, maximum: 58}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
    
end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:edit, :update, :show, :destroy]

    def index
        @articles = Article.all
    end
   
    def new

        @article = Article.new
        
    end

    def edit
        
    end

    
    def create

        @article = Article.new(article_params)
        
            if @article.save
        
                flash[:notice] = "Article was successfully created"
        
                redirect_to article_path(@article)
        
            else
        
                render 'new'
        
            end
        
    end


    def update
       
        if @article.update(article_params)
            flash[:notice] = "Article was successfully updated"
            redirect_to article_path(@article)
        else
            render 'edit'
        end

    end

    def show
      
    end

    def destroy
      
        @article.destroy
        flash[:notice] = "Article was successfully deleted"
        redirect_to articles_path
    end


    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end


 


end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

    def home
    end
    def about
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>The following errors prevented the article from getting created</h2>
<ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <%end%>
</ul>
<%end%>


<%= form_for @article do |f| %>
    <p>
        <%= f.label :title %> <br/>
        <%= f.text_field :title %>
    </p>

    
    <p>
        <%= f.label :description %> <br/>
        <%= f.text_area :description %>
    </p>

    <p>
        <%= f.submit %>
    </p>

    
<% end %>

<%= link_to "Back to articles listing", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= render 'form' %>




app/views/articles/index.html.erb

<h1>Listing all articles</h1>
<p>
    <%= link_to "Create new article", new_article_path %>
</p>

<table>
    <tr>
        <th>Title</th>
        <th>Description</th>
    </tr>
<% @articles.each do |article| %>

<tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
 

</tr>

<% end %>

</table>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>


app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p>Title: <%= @article.title %></p>

<p>
Description: <%= @article.description %>
</p>


<%= link_to "Edit this article", edit_article_path(@article)%> |
<%= link_to "Back to articles listing", articles_path %>

app/views/layouts/_messages.html.erb
<%flash.each do |name, msg| %>
        <ul>
          <li><%= msg%> </li>
        <ul/>
    <%end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MugiBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>  
    
    <%= yield %>

   
    <%#= debug(params) if Rails.env.development? %>
    
  </body>
</html>

app/views/welcomes/about.html.erb
<h1>Hello this is About page</h1>

<%= link_to 'Home', root_path %>

app/views/welcomes/home.html.erb
<h1>This is homepage</h1>
<%= link_to 'Articles Page', articles_path%> | <%= link_to 'About', about_path%>